EVENT_STAGE = "STAGE"

EVENT_PROGRESS = "PROGRESS"

EVENT_SITE_START = "SITE_START"

EVENT_SITE_PROGRESS = "SITE_PROGRESS"

EVENT_SITE_COMPLETE = "SITE_COMPLETE"

EVENT_SWEEP_COMPLETE = "SWEEP_COMPLETE"

EVENT_SWEEP_CANCELLED = "SWEEP_CANCELLED"