EVENT_STAGE = "stage"
EVENT_SITE_START = "site_start"
EVENT_PROGRESS = "progress"
EVENT_SITE_COMPLETE = "site_complete"

EVENT_SWEEP_COMPLETE = "SWEEP_COMPLETE"
EVENT_SWEEP_CANCELLED = "SWEEP_CANCELLED"